# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "sunrise" # Options: "default", "air", "contrast", "dark", "dirt", "mint", "sunrise"

# Site Settings
title: "Rebrandon's Journey to a Shiny Living Dex <i class='fas fa-sparkles' style='color: #f1c40f;'></i>" # This appears in the top left 'Logo' area
name: "Brandon"           # This appears in your sidebar profile
description: "Documenting my journey to catch 'em all in sparkles."
url: "https://rebrandon.github.io" 
baseurl: "" # Leave empty unless your repo is NOT named [username].github.io

# Site Icons
favicon: "/assets/images/favicon.ico"
apple_touch_icon: "/assets/images/apple-touch-icon.png"

# Build Settings
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Sidebar/Author Settings
search: true
author:
  name: "Brandon the Slaking Master"
  avatar: "/assets/images/website pic 1.png"
  bio: |
    Shiny Hunter
    
    **Living Dex: 215/1025**
    <div style="background: #eee; border-radius: 5px; height: 10px; width: 100%; margin-top: 5px;">
      <div style="background: #fb8c00; height: 10px; width: 21%; border-radius: 5px;"></div>
    </div>

    ---
    **üéØ Active Hunts**
    * üí™üèª **Buzzwole**: 221 (US/UM Wormhole SRs)

  location: "Paldea"
  links:
    - label: "BlueSky"
      icon: "fab fa-fw fa-cloud"
      url: "https://bsky.app/profile/rebrandon.bsky.social"
    - label: "PokeDexTracker"
      icon: "fas fa-fw fa-th"
      url: "https://pokedextracker.com/u/rebrandon"
# Defaults for Posts (The "Blog" Experience)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
      
 
